{{- if .Values.ingress.panel.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sharx.fullname" . }}-panel
  labels:
    {{- include "sharx.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.panel.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.panel.className }}
  ingressClassName: {{ .Values.ingress.panel.className | quote }}
  {{- end }}
  {{- if .Values.ingress.panel.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.panel.host | quote }}
      secretName: {{ printf "%s-panel-tls" (include "sharx.fullname" .) }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.panel.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "sharx.fullname" . }}
                port:
                  number: {{ .Values.panel.env.webPort | int }}
{{- end }}
---
{{- if .Values.ingress.sub.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sharx.fullname" . }}-sub
  labels:
    {{- include "sharx.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.sub.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.sub.className }}
  ingressClassName: {{ .Values.ingress.sub.className | quote }}
  {{- end }}
  {{- if .Values.ingress.sub.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.sub.host | quote }}
      secretName: {{ printf "%s-sub-tls" (include "sharx.fullname" .) }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.sub.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "sharx.fullname" . }}
                port:
                  number: {{ .Values.panel.env.subPort | int }}
{{- end }}
