{{- if .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.existingSecret }}
  labels:
    {{- include "sharx.labels" . | nindent 4 }}
type: Opaque
stringData:
  XUI_DB_PASSWORD: {{ .Values.auth.dbPassword | required "auth.dbPassword is required when auth.createSecret=true" | quote }}
  POSTGRES_PASSWORD: {{ .Values.auth.dbPassword | quote }}
  POSTGRES_USER: {{ .Values.panel.env.dbUser | quote }}
  POSTGRES_DB: {{ .Values.panel.env.dbName | quote }}
{{- end }}
