apiVersion: v2
name: sharx
description: SharX panel — umbrella chart (secret + uc)
type: application
version: 0.2.0
appVersion: "latest"
dependencies:
  - name: secret
    alias: secret
    version: 1.1.0
    repository: file://../../../../lib/secret
  - name: uc
    alias: panel
    version: 1.0.0
    repository: file://../../../../lib/uc
  - name: uc
    alias: postgres
    version: 1.0.0
    repository: file://../../../../lib/uc
